import { CARD_DEFINITIONS, MARKET_CARD_IDS, STARTER_CARD_IDS, cardDef } from './data/cards.js';
import { CHARACTERS } from './data/characters.js';
import { MILESTONE_REWARDS, PHASES, RULES, ZONES } from './data/constants.js';
let nextCardId=1;
export function createRng(seed=Date.now()){let v=seed>>>0;return()=>{v=(v*1664525+1013904223)>>>0;return v/0x100000000;};}
export function shuffle(items,rng=Math.random){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
export function createCardInstance(definitionId,ownerId,source='setup'){return{id:`card-${nextCardId++}`,definitionId,ownerId,source,zone:ZONES.DECK};}
export const resetCardIds=(v=1)=>{nextCardId=v;}; export const getNextCardId=()=>nextCardId; export const setNextCardId=(v)=>{nextCardId=Math.max(1,Number(v)||1);};
const clone=(s)=>structuredClone(s); const findPlayer=(s,id)=>s.players.find(p=>p.id===id);
function addLog(s,message){return{...s,log:[{id:`log-${s.log.length+1}`,message,at:Date.now()},...s.log].slice(0,80)};}
function addRewardDecision(s,decision){const history=s.rewardHistory||[];return{...s,rewardHistory:[{id:`reward-${Date.now()}-${history.length+1}`,duelNumber:s.duelNumber,...decision},...history].slice(0,50)};}
function setupDeck(p,ids,rng,source){p.deck=shuffle(ids.map(id=>createCardInstance(id,p.id,source)),rng);p.deck.forEach(c=>c.zone=ZONES.DECK);}
function drawOne(p,rng){if(!p.deck.length&&p.rest.length){p.deck=shuffle(p.rest.map(c=>({...c,zone:ZONES.DECK})),rng);p.rest=[];}const c=p.deck.pop();if(!c)return null;c.zone=ZONES.HAND;p.hand.push(c);return c;}
export function fillHand(p,rng,size=RULES.startingHandSize){while(!p.neutral&&p.hand.length<size){if(!drawOne(p,rng))break;}}
function makePlayer(c,index,{human=false,neutral=false}={}){return{id:neutral?'panda-master':`player-${index+1}`,name:c.name,animal:c.animal,portrait:c.portrait,color:c.color,line:c.line,winLine:c.winLine,human,ai:!human,neutral,fame:0,experience:0,deck:[],hand:[],rest:[],mastered:[],consumed:[],played:[],finalPower:0,seat:index,boughtThisDuel:false};}
export function createGame({playerCount=2,seed=Date.now(),targetFame=RULES.targetFame,milestoneMode=RULES.milestoneMode}={}){resetCardIds(1);const rng=createRng(seed);const n=Math.max(2,Math.min(4,playerCount));const target=Math.max(12,Math.min(100,Number(targetFame)||RULES.targetFame));const players=Array.from({length:n},(_,i)=>makePlayer(CHARACTERS[i],i,{human:i===0}));players.forEach((p,i)=>{p.seat=i;setupDeck(p,STARTER_CARD_IDS,rng,'starter');fillHand(p,rng);});const vi=Math.floor(rng()*players.length);const s={version:1,actionProtocolVersion:1,phase:PHASES.WAITING_FOR_CARD,rules:{...RULES,targetFame:target,milestoneMode:Boolean(milestoneMode)},settings:{animationSpeed:1,playerCount:n},seed,rngSeed:Math.floor(rng()*0xffffffff),trainingCycle:1,duelNumber:1,actingPlayerId:players[vi].id,vanguardPlayerId:players[vi].id,seatOrder:players.map(p=>p.id),players,market:Object.fromEntries(MARKET_CARD_IDS.map(id=>[id,CARD_DEFINITIONS[id].marketCount])),duel:{plays:[],winnerId:null,highestPower:0,masteredCardId:null,experienceGains:[],loserActions:[]},pending:{winnerReward:null,masteryCards:[],loserQueue:[],loserActionPlayerId:null,recapAcknowledgedPlayerIds:[],milestoneQueue:[],milestoneCurrent:null,milestoneResume:null,milestoneFallbackQueue:[],milestoneActivePlayerId:null},milestones:{claimed:{},history:[]},winnerId:null,inputLocked:false,log:[],rewardHistory:[],nextCardId:getNextCardId()};return addLog(s,`${players[vi].name}이 선봉패를 잡았습니다.`);}
export function reviveGame(raw){if(!raw||raw.version!==1||!Array.isArray(raw.players))return null;let s=clone(raw);s.inputLocked=false;s.actionProtocolVersion=s.actionProtocolVersion||1;s.rewardHistory=Array.isArray(s.rewardHistory)?s.rewardHistory:[];s.milestones=s.milestones&&typeof s.milestones==='object'?s.milestones:{claimed:{},history:[]};s.milestones.claimed=s.milestones.claimed||{};s.milestones.history=Array.isArray(s.milestones.history)?s.milestones.history:[];s.rules.milestoneMode=s.rules.milestoneMode??true;s.duel.experienceGains=Array.isArray(s.duel.experienceGains)?s.duel.experienceGains:[];s.duel.loserActions=Array.isArray(s.duel.loserActions)?s.duel.loserActions:[];s.pending.recapAcknowledgedPlayerIds=Array.isArray(s.pending.recapAcknowledgedPlayerIds)?s.pending.recapAcknowledgedPlayerIds:[];s.pending.milestoneQueue=Array.isArray(s.pending.milestoneQueue)?s.pending.milestoneQueue:[];s.pending.milestoneFallbackQueue=Array.isArray(s.pending.milestoneFallbackQueue)?s.pending.milestoneFallbackQueue:[];setNextCardId(s.nextCardId||1);if(s.winnerId){s.phase=PHASES.GAME_OVER;return s;}if(s.phase===PHASES.RESOLVING_DUEL){if(s.duel?.plays?.length===s.seatOrder?.length)return resolveDuel(s);return null;}if(s.phase===PHASES.REFILLING_HANDS)return finishDuel(s);return s;}
function advanceRng(s,rng){s.rngSeed=Math.floor(rng()*0xffffffff);}
function revealFromDeck(p,rng){if(!p.deck.length&&p.rest.length){p.deck=shuffle(p.rest.map(c=>({...c,zone:ZONES.DECK})),rng);p.rest=[];}const c=p.deck.pop();if(!c)return null;c.zone=ZONES.PLAY;return c;}
function resolvePlayedCards(s,p,initial,rng){const cards=[{...initial,zone:ZONES.PLAY}];let power=cardDef(initial).power,cursor=initial,guard=0;while(cardDef(cursor).ability==='combo'&&guard<100){guard++;const n=revealFromDeck(p,rng);if(!n){s=addLog(s,`${p.name}의 연계 자세가 이어질 기술을 찾지 못했습니다.`);break;}cards.push(n);power+=cardDef(n).power;s=addLog(s,`${p.name}의 연계 자세로 ${cardDef(n).name}이 이어졌습니다.`);cursor=n;}return{state:s,cards,totalPower:power};}
function nextActingPlayer(s){const i=s.seatOrder.indexOf(s.actingPlayerId);for(let o=1;o<=s.seatOrder.length;o++){const id=s.seatOrder[(i+o)%s.seatOrder.length];if(!s.duel.plays.some(x=>x.playerId===id))return id;}return null;}
export function playCard(state,playerId,cardId=null){if(state.phase!==PHASES.WAITING_FOR_CARD||state.actingPlayerId!==playerId||state.inputLocked||state.winnerId)return state;let s=clone(state);let p=findPlayer(s,playerId);const rng=createRng(s.rngSeed);let card;if(p.neutral)card=revealFromDeck(p,rng);else{const i=p.hand.findIndex(c=>c.id===cardId);if(i<0)return state;card=p.hand.splice(i,1)[0];card.zone=ZONES.PLAY;}if(!card)return state;const r=resolvePlayedCards(s,p,card,rng);s=r.state;advanceRng(s,rng);p=findPlayer(s,playerId);p.played.push(...r.cards);p.finalPower=r.totalPower;s.duel.plays.push({playerId,cardIds:r.cards.map(c=>c.id),cards:r.cards,totalPower:r.totalPower,order:s.duel.plays.length});s.duel.highestPower=Math.max(s.duel.highestPower,r.totalPower);s=addLog(s,`${p.name}이 ${cardDef(card).name} ${cardDef(card).power}을 사용했습니다. 최종 위력은 ${r.totalPower}입니다.`);const f=nextActingPlayer(s);if(f){s.actingPlayerId=f;return{...s,nextCardId:getNextCardId()};}return resolveDuel(s);}
export function resolveDuel(state){let s=clone(state);if(!s.duel.plays.length)return s;s.phase=PHASES.RESOLVING_DUEL;const wp=[...s.duel.plays].sort((a,b)=>a.totalPower===b.totalPower?b.order-a.order:b.totalPower-a.totalPower)[0];const w=findPlayer(s,wp.playerId);s.duel.winnerId=w.id;s.vanguardPlayerId=w.id;s.actingPlayerId=w.id;s=addLog(s,`${w.name}이 대련에서 승리했습니다.`);if(w.neutral)return chooseWinnerReward(s,'fame');const mc=getMasteryCandidates(s,w.id);s.pending.winnerReward={playerId:w.id,fameGain:wp.totalPower,canMaster:mc.length>0};s.pending.masteryCards=mc;s.phase=PHASES.WAITING_FOR_WINNER_REWARD;return s;}
function reusableCardCount(p){return p.deck.length+p.hand.length+p.rest.length+p.played.filter(c=>!cardDef(c).exhausts).length;}
export function getMasteryCandidates(s,id){const p=findPlayer(s,id);if(!p||p.neutral)return[];const reusable=reusableCardCount(p);if(reusable-1<s.rules.minimumReusableCardsAfterMastery)return[];return[...p.rest,...(s.rules.allowPlayedCardMastery?p.played:[])].filter(c=>!cardDef(c).exhausts).map(c=>({id:c.id,definitionId:c.definitionId,name:cardDef(c).name,power:cardDef(c).power,zone:p.rest.some(x=>x.id===c.id)?ZONES.REST:ZONES.PLAY,remainingReusable:reusable-1}));}
function milestoneOwnedCards(p){return[[ZONES.DECK,p.deck],[ZONES.HAND,p.hand],[ZONES.REST,p.rest],[ZONES.PLAY,p.played]].flatMap(([zone,cards])=>cards.filter(c=>!cardDef(c).exhausts).map(c=>({card:c,zone})));}
export function getMilestoneMasteryCandidates(s,id){const p=findPlayer(s,id);if(!p||p.neutral)return[];const owned=milestoneOwnedCards(p);if(owned.length<=s.rules.minimumReusableCardsAfterMastery)return[];return owned.filter(({zone})=>zone!==ZONES.HAND).map(({card,zone})=>({id:card.id,definitionId:card.definitionId,name:cardDef(card).name,power:cardDef(card).power,zone,remainingReusable:owned.length-1}));}
function removeMilestoneCard(s,playerId,cardId){const p=findPlayer(s,playerId);const candidate=getMilestoneMasteryCandidates(s,playerId).find(c=>c.id===cardId);if(!candidate)return null;const key=candidate.zone===ZONES.PLAY?'played':candidate.zone;const index=p[key].findIndex(c=>c.id===cardId);if(index<0)return null;const[card]=p[key].splice(index,1);p.mastered.push({...card,zone:ZONES.MASTERED});return candidate;}
function updateMilestoneHistory(s,id,patch){s.milestones.history=s.milestones.history.map(item=>item.id===id?{...item,...patch}:item);}
function resumeAfterMilestones(state){let s=clone(state);const resume=s.pending.milestoneResume;s.pending.milestoneQueue=[];s.pending.milestoneCurrent=null;s.pending.milestoneResume=null;s.pending.milestoneFallbackQueue=[];s.pending.milestoneActivePlayerId=null;if(!resume)return s;const p=findPlayer(s,resume.playerId);s=checkImmediateWin(s,p);if(s.phase===PHASES.GAME_OVER)return s;if(resume.kind==='winner-fame')return beginLoserActions(s);if(resume.kind==='loser-action')return completeLoserAction(s,resume.playerId);return s;}
function advanceMilestoneQueue(state){let s=clone(state);while(s.pending.milestoneQueue.length){const reward=s.pending.milestoneQueue[0];const claimant=findPlayer(s,reward.playerId);if(reward.type==='experience'){const before=claimant.experience;claimant.experience=Math.min(s.rules.maxExperience,claimant.experience+reward.amount);const gained=claimant.experience-before;updateMilestoneHistory(s,reward.historyId,{status:'resolved',experienceGained:gained});s=addLog(s,`${claimant.name}이 명성 ${reward.score} 선착 보상으로 경험치 ${gained}을 얻었습니다.`);s.pending.milestoneQueue.shift();continue;}const candidates=getMilestoneMasteryCandidates(s,claimant.id);s.pending.milestoneCurrent=reward;if(candidates.length){s.pending.milestoneActivePlayerId=claimant.id;s.phase=PHASES.WAITING_FOR_MILESTONE_MASTERY;return s;}s.pending.milestoneFallbackQueue=s.seatOrder.filter(id=>id!==claimant.id&&!findPlayer(s,id).neutral);s.pending.milestoneActivePlayerId=s.pending.milestoneFallbackQueue[0]||null;updateMilestoneHistory(s,reward.historyId,{status:'fallback',fallbackChoices:[]});s=addLog(s,`${claimant.name}은 카드가 ${s.rules.minimumReusableCardsAfterMastery}장 이하여서 다른 참가자들이 체득 기회를 얻습니다.`);if(s.pending.milestoneActivePlayerId){s.phase=PHASES.WAITING_FOR_MILESTONE_FALLBACK;return s;}s.pending.milestoneQueue.shift();}return resumeAfterMilestones(s);}
function triggerMilestones(state,playerId,beforeFame,resume){let s=clone(state);const p=findPlayer(s,playerId);if(p.fame>=s.rules.targetFame)return checkImmediateWin(s,p);if(!s.rules.milestoneMode)return resume.kind==='winner-fame'?beginLoserActions(s):completeLoserAction(s,resume.playerId);const rewards=MILESTONE_REWARDS.filter(reward=>reward.score>beforeFame&&reward.score<=p.fame&&reward.score<s.rules.targetFame&&!s.milestones.claimed[reward.score]);if(!rewards.length)return resume.kind==='winner-fame'?beginLoserActions(s):completeLoserAction(s,resume.playerId);s.pending.milestoneResume=resume;for(const reward of rewards){const historyId=`milestone-${reward.score}`;s.milestones.claimed[reward.score]=p.id;s.milestones.history=[{id:historyId,score:reward.score,playerId:p.id,rewardType:reward.type,amount:reward.amount,status:'claimed',duelNumber:s.duelNumber},...s.milestones.history];s.pending.milestoneQueue.push({...reward,playerId:p.id,historyId});s=addLog(s,`${p.name}이 명성 ${reward.score}에 가장 먼저 도달했습니다.`);}return advanceMilestoneQueue(s);}
export function resolveMilestoneMastery(state,playerId,cardId){if(state.phase!==PHASES.WAITING_FOR_MILESTONE_MASTERY||state.pending.milestoneActivePlayerId!==playerId)return state;let s=clone(state);const reward=s.pending.milestoneCurrent;const card=removeMilestoneCard(s,playerId,cardId);if(!card)return state;updateMilestoneHistory(s,reward.historyId,{status:'resolved',cardId,cardName:card.name});s=addLog(s,`${findPlayer(s,playerId).name}이 선착 보상으로 ${card.name}을 체득했습니다.`);s.pending.milestoneQueue.shift();s.pending.milestoneCurrent=null;s.pending.milestoneActivePlayerId=null;return advanceMilestoneQueue(s);}
export function resolveMilestoneFallback(state,playerId,cardId=null){if(state.phase!==PHASES.WAITING_FOR_MILESTONE_FALLBACK||state.pending.milestoneActivePlayerId!==playerId)return state;let s=clone(state);const reward=s.pending.milestoneCurrent;const player=findPlayer(s,playerId);let card=null;if(cardId)card=removeMilestoneCard(s,playerId,cardId);const record=s.milestones.history.find(item=>item.id===reward.historyId);const choices=[...(record?.fallbackChoices||[]),{playerId,choice:card?'mastery':'skip',cardId:card?.id||null,cardName:card?.name||null}];updateMilestoneHistory(s,reward.historyId,{fallbackChoices:choices});s=addLog(s,card?`${player.name}이 양도된 기회로 ${card.name}을 체득했습니다.`:`${player.name}이 양도된 체득 기회를 넘겼습니다.`);s.pending.milestoneFallbackQueue=s.pending.milestoneFallbackQueue.filter(id=>id!==playerId);s.pending.milestoneActivePlayerId=s.pending.milestoneFallbackQueue[0]||null;if(s.pending.milestoneActivePlayerId)return s;updateMilestoneHistory(s,reward.historyId,{status:'resolved'});s.pending.milestoneQueue.shift();s.pending.milestoneCurrent=null;return advanceMilestoneQueue(s);}
function checkImmediateWin(s,p){return p.fame>=s.rules.targetFame?addLog({...s,winnerId:p.id,phase:PHASES.GAME_OVER},`${p.name}이 명성 ${p.fame}에 도달했습니다.`):s;}
export function chooseWinnerReward(state,type){const neutral=findPlayer(state,state.duel.winnerId)?.neutral;if(state.phase!==PHASES.WAITING_FOR_WINNER_REWARD&&!neutral)return state;let s=clone(state);const w=findPlayer(s,s.duel.winnerId);const wp=s.duel.plays.find(x=>x.playerId===w.id);if(type==='mastery'&&getMasteryCandidates(s,w.id).length){s.phase=PHASES.WAITING_FOR_MASTERY_CARD;return s;}const before=w.fame;w.fame+=wp.totalPower;s=addRewardDecision(s,{playerId:w.id,choice:'fame',amount:wp.totalPower});s=addLog(s,`${w.name}이 명성 ${wp.totalPower}을 얻었습니다.`);return triggerMilestones(s,w.id,before,{kind:'winner-fame',playerId:w.id});}
export function masterCard(state,cardId){if(state.phase!==PHASES.WAITING_FOR_MASTERY_CARD)return state;let s=clone(state);const w=findPlayer(s,s.duel.winnerId);const c=getMasteryCandidates(s,w.id).find(x=>x.id===cardId);if(!c)return state;s.duel.masteredCardId=cardId;s=addRewardDecision(s,{playerId:w.id,choice:'mastery',cardId,cardDefinitionId:c.definitionId,cardName:c.name});s=addLog(s,`${w.name}이 ${c.name}을 완전히 체득했습니다.`);return beginLoserActions(s);}
function prepareDuelRecap(state){let s=clone(state);s.phase=PHASES.WAITING_FOR_DUEL_RECAP;s.pending.loserActionPlayerId=null;s.pending.recapAcknowledgedPlayerIds=[];return{...s,nextCardId:getNextCardId()};}
function beginLoserActions(state){let s=clone(state);const wid=s.duel.winnerId;s.duel.experienceGains=[];for(const play of s.duel.plays){const p=findPlayer(s,play.playerId);if(p.id!==wid&&!p.neutral){const before=p.experience;p.experience=Math.min(s.rules.maxExperience,p.experience+play.totalPower);const amount=p.experience-before;s.duel.experienceGains.push({playerId:p.id,amount});s=addLog(s,`${p.name}이 실전 경험 ${amount}을 얻었습니다.`);}}const start=(s.seatOrder.indexOf(s.vanguardPlayerId)+1)%s.seatOrder.length;const ordered=[...s.seatOrder.slice(start),...s.seatOrder.slice(0,start)];const q=ordered.filter(id=>id!==wid&&!findPlayer(s,id).neutral);s.pending.loserQueue=q;s.pending.loserActionPlayerId=q[0]||null;s.phase=q.length?PHASES.WAITING_FOR_LOSER_ACTION:PHASES.WAITING_FOR_DUEL_RECAP;return q.length?s:prepareDuelRecap(s);}
function completeLoserAction(state,id){let s=clone(state);s.pending.loserQueue=s.pending.loserQueue.filter(x=>x!==id);s.pending.loserActionPlayerId=s.pending.loserQueue[0]||null;if(s.pending.loserActionPlayerId){s.phase=PHASES.WAITING_FOR_LOSER_ACTION;return{...s,nextCardId:getNextCardId()};}return prepareDuelRecap(s);}
export function loserAction(state,id,action){if(state.phase!==PHASES.WAITING_FOR_LOSER_ACTION||state.pending.loserActionPlayerId!==id)return state;let s=clone(state);const p=findPlayer(s,id);let summary;if(action.type==='buy'){const d=CARD_DEFINITIONS[action.cardDefinitionId];if(!d||p.boughtThisDuel||s.market[d.id]<=0||p.experience<d.cost)return state;p.experience-=d.cost;p.boughtThisDuel=true;s.market[d.id]--;const c=createCardInstance(d.id,p.id,'market');c.zone=ZONES.REST;p.rest.push(c);summary={playerId:id,type:'buy',cardDefinitionId:d.id,cardName:d.name,cost:d.cost};s=addLog(s,`${p.name}이 ${d.name}을 수련했습니다.`);}else if(action.type==='train-fame'){if(p.experience<s.rules.trainingExperienceCost)return state;const before=p.fame;p.experience-=s.rules.trainingExperienceCost;p.fame+=s.rules.trainingFameGain;summary={playerId:id,type:'train-fame',cost:s.rules.trainingExperienceCost,fameGain:s.rules.trainingFameGain};s=addLog(s,`${p.name}이 명성 훈련으로 명성 ${s.rules.trainingFameGain}을 얻었습니다.`);s.duel.loserActions=[...(s.duel.loserActions||[]),summary];return triggerMilestones(s,p.id,before,{kind:'loser-action',playerId:id});}else{summary={playerId:id,type:'rest'};s=addLog(s,`${p.name}이 경험을 아껴 두었습니다.`);}s.duel.loserActions=[...(s.duel.loserActions||[]),summary];return completeLoserAction(s,id);}
export function confirmDuelRecap(state,playerId){if(state.phase!==PHASES.WAITING_FOR_DUEL_RECAP)return state;let s=clone(state);const humans=s.players.filter(p=>p.human).map(p=>p.id);const required=humans.length?humans:[playerId];if(!s.players.some(p=>p.id===playerId)||!required.includes(playerId))return state;const acknowledged=new Set(s.pending.recapAcknowledgedPlayerIds||[]);acknowledged.add(playerId);s.pending.recapAcknowledgedPlayerIds=[...acknowledged];return required.every(id=>acknowledged.has(id))?finishDuel(s):s;}
function movePlayedCards(p,masteredId){const moved=[];for(const c of p.played){if(c.id===masteredId)p.mastered.push({...c,zone:ZONES.MASTERED});else if(cardDef(c).exhausts)p.consumed.push({...c,zone:ZONES.CONSUMED});else p.rest.push({...c,zone:ZONES.REST});moved.push(c.id);}if(masteredId&&!moved.includes(masteredId)){const i=p.rest.findIndex(c=>c.id===masteredId);if(i>=0){const[c]=p.rest.splice(i,1);p.mastered.push({...c,zone:ZONES.MASTERED});}}p.played=[];p.finalPower=0;p.boughtThisDuel=false;}
export function finishDuel(state){let s=clone(state);for(const p of s.players)movePlayedCards(p,s.duel.masteredCardId);const rng=createRng(s.rngSeed);const normals=s.players.filter(p=>!p.neutral);const allEmpty=normals.every(p=>p.hand.length===0);if(allEmpty){for(const p of normals)fillHand(p,rng);s.trainingCycle++;s=addLog(s,`${s.trainingCycle}번째 수련 주기를 시작합니다.`);}else if(normals.some(p=>p.hand.length===0)){s=addLog(s,'손패 상태가 어긋나 수련 주기를 유지합니다. 빈 손패 참가자는 다음 대련 전에 복구가 필요합니다.');}
advanceRng(s,rng);s.duelNumber++;s.duel={plays:[],winnerId:null,highestPower:0,masteredCardId:null,experienceGains:[],loserActions:[]};s.pending={winnerReward:null,masteryCards:[],loserQueue:[],loserActionPlayerId:null,recapAcknowledgedPlayerIds:[],milestoneQueue:[],milestoneCurrent:null,milestoneResume:null,milestoneFallbackQueue:[],milestoneActivePlayerId:null};s.actingPlayerId=s.vanguardPlayerId;s.phase=PHASES.WAITING_FOR_CARD;return{...s,nextCardId:getNextCardId()};}
export const setInputLocked=(s,v)=>({...s,inputLocked:Boolean(v)});
