import { CARD_DEFINITIONS, MARKET_CARD_IDS, STARTER_CARD_IDS, cardDef } from './data/cards.js';
import { CHARACTERS, PANDA_MASTER } from './data/characters.js';
import { PHASES, RULES, ZONES } from './data/constants.js';
let nextCardId=1;
export function createRng(seed=Date.now()){let v=seed>>>0;return()=>{v=(v*1664525+1013904223)>>>0;return v/0x100000000;};}
export function shuffle(items,rng=Math.random){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
export function createCardInstance(definitionId,ownerId,source='setup'){return{id:`card-${nextCardId++}`,definitionId,ownerId,source,zone:ZONES.DECK};}
export const resetCardIds=(v=1)=>{nextCardId=v;}; export const getNextCardId=()=>nextCardId; export const setNextCardId=(v)=>{nextCardId=Math.max(1,Number(v)||1);};
const clone=(s)=>structuredClone(s); const findPlayer=(s,id)=>s.players.find(p=>p.id===id);
function addLog(s,message){return{...s,log:[{id:`log-${s.log.length+1}`,message,at:Date.now()},...s.log].slice(0,80)};}
function setupDeck(p,ids,rng,source){p.deck=shuffle(ids.map(id=>createCardInstance(id,p.id,source)),rng);p.deck.forEach(c=>c.zone=ZONES.DECK);}
function drawOne(p,rng){if(!p.deck.length&&p.rest.length){p.deck=shuffle(p.rest.map(c=>({...c,zone:ZONES.DECK})),rng);p.rest=[];}const c=p.deck.pop();if(!c)return null;c.zone=ZONES.HAND;p.hand.push(c);return c;}
export function fillHand(p,rng,size=RULES.startingHandSize){while(!p.neutral&&p.hand.length<size){if(!drawOne(p,rng))break;}}
function makePlayer(c,index,{human=false,neutral=false}={}){return{id:neutral?'panda-master':`player-${index+1}`,name:c.name,animal:c.animal,portrait:c.portrait,color:c.color,line:c.line,winLine:c.winLine,human,ai:!human,neutral,fame:0,experience:0,deck:[],hand:[],rest:[],mastered:[],consumed:[],played:[],finalPower:0,seat:index,boughtThisDuel:false};}
export function createGame({playerCount=2,seed=Date.now()}={}){resetCardIds(1);const rng=createRng(seed);const n=Math.max(2,Math.min(4,playerCount));const normals=Array.from({length:n},(_,i)=>makePlayer(CHARACTERS[i],i,{human:i===0}));const players=n===2?[normals[0],makePlayer(PANDA_MASTER,1,{neutral:true}),normals[1]]:normals;players.forEach((p,i)=>{p.seat=i;if(p.neutral)setupDeck(p,[...STARTER_CARD_IDS,'combo_stance','bunny_kick','tail_spin','maple_combo','headbutt'],rng,'panda');else{setupDeck(p,STARTER_CARD_IDS,rng,'starter');fillHand(p,rng);}});const vi=Math.floor(rng()*players.length);const s={version:1,phase:PHASES.WAITING_FOR_CARD,rules:{...RULES},settings:{animationSpeed:1,muted:false,volume:.5,playerCount:n},seed,rngSeed:Math.floor(rng()*0xffffffff),trainingCycle:1,duelNumber:1,actingPlayerId:players[vi].id,vanguardPlayerId:players[vi].id,seatOrder:players.map(p=>p.id),players,market:Object.fromEntries(MARKET_CARD_IDS.map(id=>[id,CARD_DEFINITIONS[id].marketCount])),duel:{plays:[],winnerId:null,highestPower:0,masteredCardId:null},pending:{winnerReward:null,masteryCards:[],loserQueue:[],loserActionPlayerId:null},winnerId:null,inputLocked:false,log:[],nextCardId:getNextCardId()};return addLog(s,`${players[vi].name}이 선봉패를 잡았습니다.`);}
export function reviveGame(raw){if(!raw||raw.version!==1||!Array.isArray(raw.players))return null;let s=clone(raw);s.inputLocked=false;setNextCardId(s.nextCardId||1);if(s.winnerId){s.phase=PHASES.GAME_OVER;return s;}if(s.phase===PHASES.RESOLVING_DUEL){if(s.duel?.plays?.length===s.seatOrder?.length)return resolveDuel(s);return null;}if(s.phase===PHASES.REFILLING_HANDS)return finishDuel(s);return s;}
function advanceRng(s,rng){s.rngSeed=Math.floor(rng()*0xffffffff);}
function revealFromDeck(p,rng){if(!p.deck.length&&p.rest.length){p.deck=shuffle(p.rest.map(c=>({...c,zone:ZONES.DECK})),rng);p.rest=[];}const c=p.deck.pop();if(!c)return null;c.zone=ZONES.PLAY;return c;}
function resolvePlayedCards(s,p,initial,rng){const cards=[{...initial,zone:ZONES.PLAY}];let power=cardDef(initial).power,cursor=initial,guard=0;while(cardDef(cursor).ability==='combo'&&guard<100){guard++;const n=revealFromDeck(p,rng);if(!n){s=addLog(s,`${p.name}의 연계 자세가 이어질 기술을 찾지 못했습니다.`);break;}cards.push(n);power+=cardDef(n).power;s=addLog(s,`${p.name}의 연계 자세로 ${cardDef(n).name}이 이어졌습니다.`);cursor=n;}return{state:s,cards,totalPower:power};}
function nextActingPlayer(s){const i=s.seatOrder.indexOf(s.actingPlayerId);for(let o=1;o<=s.seatOrder.length;o++){const id=s.seatOrder[(i+o)%s.seatOrder.length];if(!s.duel.plays.some(x=>x.playerId===id))return id;}return null;}
export function playCard(state,playerId,cardId=null){if(state.phase!==PHASES.WAITING_FOR_CARD||state.actingPlayerId!==playerId||state.inputLocked||state.winnerId)return state;let s=clone(state);let p=findPlayer(s,playerId);const rng=createRng(s.rngSeed);let card;if(p.neutral)card=revealFromDeck(p,rng);else{const i=p.hand.findIndex(c=>c.id===cardId);if(i<0)return state;card=p.hand.splice(i,1)[0];card.zone=ZONES.PLAY;}if(!card)return state;const r=resolvePlayedCards(s,p,card,rng);s=r.state;advanceRng(s,rng);p=findPlayer(s,playerId);p.played.push(...r.cards);p.finalPower=r.totalPower;s.duel.plays.push({playerId,cardIds:r.cards.map(c=>c.id),cards:r.cards,totalPower:r.totalPower,order:s.duel.plays.length});s.duel.highestPower=Math.max(s.duel.highestPower,r.totalPower);s=addLog(s,`${p.name}이 ${cardDef(card).name} ${cardDef(card).power}을 사용했습니다. 최종 위력은 ${r.totalPower}입니다.`);const f=nextActingPlayer(s);if(f){s.actingPlayerId=f;return{...s,nextCardId:getNextCardId()};}return resolveDuel(s);}
export function resolveDuel(state){let s=clone(state);if(!s.duel.plays.length)return s;s.phase=PHASES.RESOLVING_DUEL;const wp=[...s.duel.plays].sort((a,b)=>a.totalPower===b.totalPower?b.order-a.order:b.totalPower-a.totalPower)[0];const w=findPlayer(s,wp.playerId);s.duel.winnerId=w.id;s.vanguardPlayerId=w.id;s.actingPlayerId=w.id;s=addLog(s,`${w.name}이 대련에서 승리했습니다.`);if(w.neutral)return chooseWinnerReward(s,'fame');const mc=getMasteryCandidates(s,w.id);s.pending.winnerReward={playerId:w.id,fameGain:wp.totalPower,canMaster:mc.length>0};s.pending.masteryCards=mc;s.phase=PHASES.WAITING_FOR_WINNER_REWARD;return s;}
function reusableCardCount(p){return p.deck.length+p.hand.length+p.rest.length+p.played.filter(c=>!cardDef(c).exhausts).length;}
export function getMasteryCandidates(s,id){const p=findPlayer(s,id);if(!p||p.neutral)return[];const reusable=reusableCardCount(p);if(reusable-1<s.rules.minimumReusableCardsAfterMastery)return[];return[...p.rest,...(s.rules.allowPlayedCardMastery?p.played:[])].filter(c=>!cardDef(c).exhausts).map(c=>({id:c.id,definitionId:c.definitionId,name:cardDef(c).name,power:cardDef(c).power,zone:p.rest.some(x=>x.id===c.id)?ZONES.REST:ZONES.PLAY,remainingReusable:reusable-1}));}
function checkImmediateWin(s,p){return p.fame>=s.rules.targetFame?addLog({...s,winnerId:p.id,phase:PHASES.GAME_OVER},`${p.name}이 명성 ${p.fame}에 도달했습니다.`):s;}
export function chooseWinnerReward(state,type){const neutral=findPlayer(state,state.duel.winnerId)?.neutral;if(state.phase!==PHASES.WAITING_FOR_WINNER_REWARD&&!neutral)return state;let s=clone(state);const w=findPlayer(s,s.duel.winnerId);const wp=s.duel.plays.find(x=>x.playerId===w.id);if(type==='mastery'&&getMasteryCandidates(s,w.id).length){s.phase=PHASES.WAITING_FOR_MASTERY_CARD;return s;}w.fame+=wp.totalPower;s=addLog(s,`${w.name}이 명성 ${wp.totalPower}을 얻었습니다.`);s=checkImmediateWin(s,w);return s.phase===PHASES.GAME_OVER?s:beginLoserActions(s);}
export function masterCard(state,cardId){if(state.phase!==PHASES.WAITING_FOR_MASTERY_CARD)return state;let s=clone(state);const w=findPlayer(s,s.duel.winnerId);const c=getMasteryCandidates(s,w.id).find(x=>x.id===cardId);if(!c)return state;s.duel.masteredCardId=cardId;s=addLog(s,`${w.name}이 ${c.name}을 완전히 체득했습니다.`);return beginLoserActions(s);}
function beginLoserActions(state){let s=clone(state);const wid=s.duel.winnerId;for(const play of s.duel.plays){const p=findPlayer(s,play.playerId);if(p.id!==wid&&!p.neutral){p.experience=Math.min(s.rules.maxExperience,p.experience+play.totalPower);s=addLog(s,`${p.name}이 실전 경험 ${play.totalPower}을 얻었습니다.`);}}const start=(s.seatOrder.indexOf(s.vanguardPlayerId)+1)%s.seatOrder.length;const ordered=[...s.seatOrder.slice(start),...s.seatOrder.slice(0,start)];const q=ordered.filter(id=>id!==wid&&!findPlayer(s,id).neutral);s.pending.loserQueue=q;s.pending.loserActionPlayerId=q[0]||null;s.phase=q.length?PHASES.WAITING_FOR_LOSER_ACTION:PHASES.REFILLING_HANDS;return q.length?s:finishDuel(s);}
export function loserAction(state,id,action){if(state.phase!==PHASES.WAITING_FOR_LOSER_ACTION||state.pending.loserActionPlayerId!==id)return state;let s=clone(state);const p=findPlayer(s,id);if(action.type==='buy'){const d=CARD_DEFINITIONS[action.cardDefinitionId];if(!d||p.boughtThisDuel||s.market[d.id]<=0||p.experience<d.cost)return state;p.experience-=d.cost;p.boughtThisDuel=true;s.market[d.id]--;const c=createCardInstance(d.id,p.id,'market');c.zone=ZONES.REST;p.rest.push(c);s=addLog(s,`${p.name}이 ${d.name}을 수련했습니다.`);}else if(action.type==='train-fame'){if(p.experience<s.rules.trainingExperienceCost)return state;p.experience-=s.rules.trainingExperienceCost;p.fame+=s.rules.trainingFameGain;s=addLog(s,`${p.name}이 명성 훈련으로 명성 ${s.rules.trainingFameGain}을 얻었습니다.`);s=checkImmediateWin(s,p);if(s.phase===PHASES.GAME_OVER)return s;}else s=addLog(s,`${p.name}이 경험을 아껴 두었습니다.`);s.pending.loserQueue=s.pending.loserQueue.filter(x=>x!==id);s.pending.loserActionPlayerId=s.pending.loserQueue[0]||null;s.phase=s.pending.loserActionPlayerId?PHASES.WAITING_FOR_LOSER_ACTION:PHASES.REFILLING_HANDS;return s.phase===PHASES.REFILLING_HANDS?finishDuel(s):{...s,nextCardId:getNextCardId()};}
function movePlayedCards(p,masteredId){const moved=[];for(const c of p.played){if(c.id===masteredId)p.mastered.push({...c,zone:ZONES.MASTERED});else if(cardDef(c).exhausts)p.consumed.push({...c,zone:ZONES.CONSUMED});else p.rest.push({...c,zone:ZONES.REST});moved.push(c.id);}if(masteredId&&!moved.includes(masteredId)){const i=p.rest.findIndex(c=>c.id===masteredId);if(i>=0){const[c]=p.rest.splice(i,1);p.mastered.push({...c,zone:ZONES.MASTERED});}}p.played=[];p.finalPower=0;p.boughtThisDuel=false;}
export function finishDuel(state){let s=clone(state);for(const p of s.players)movePlayedCards(p,s.duel.masteredCardId);const rng=createRng(s.rngSeed);const normals=s.players.filter(p=>!p.neutral);const allEmpty=normals.every(p=>p.hand.length===0);if(allEmpty){for(const p of normals)fillHand(p,rng);s.trainingCycle++;s=addLog(s,`${s.trainingCycle}번째 수련 주기를 시작합니다.`);}else if(normals.some(p=>p.hand.length===0)){s=addLog(s,'손패 상태가 어긋나 수련 주기를 유지합니다. 빈 손패 참가자는 다음 대련 전에 복구가 필요합니다.');}
advanceRng(s,rng);s.duelNumber++;s.duel={plays:[],winnerId:null,highestPower:0,masteredCardId:null};s.pending={winnerReward:null,masteryCards:[],loserQueue:[],loserActionPlayerId:null};s.actingPlayerId=s.vanguardPlayerId;s.phase=PHASES.WAITING_FOR_CARD;return{...s,nextCardId:getNextCardId()};}
export const setInputLocked=(s,v)=>({...s,inputLocked:Boolean(v)});
